version: "3"
services:
  cache:
    image: redis:alpine
    restart: unless-stopped
    # use this and edit REDIS_PASSWORD if you want to set a password for redis
    # command: "redis-server --requirepass ${REDIS_PASSWORD}"
    command: "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - ~/.tg_search_bot/redis/data:/data

  tg_search_bot:
    image: python:3.10
    restart: always
    working_dir: /app
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
      - ~/.tg_search_bot:/root/.tg_search_bot
    depends_on:
      - cache
    command: >
      sh -c "
      pip3 install -U -r requirements.txt && 
      python3 bot.py"
