version: "3"
services:
  cache:
    image: redis:alpine
    restart: unless-stopped
    # use this and edit password if you have a password for redis
    # command: "redis-server --requirepass ${REDIS_PASSWORD}"
    command: "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - ~/.tg_search_bot/redis/data:/data
  tg_search_bot:
    restart: always
    build: .
    volumes:
      - ~/.tg_search_bot:/root/.tg_search_bot
    depends_on:
      - cache
